version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: potions_shop
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - db_link

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adm
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    networks:
      - db_link

  back-end:
    build:
      context: ./back/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - db_link

volumes:
  mongodb_data:

networks:
  db_link: