version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $ADMIN_USER
      MONGO_INITDB_ROOT_PASSWORD: $ADMIN_PWD
      MONGO_INITDB_DATABASE: $DB_NAME
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
    networks:
      - db_link

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $ADMIN_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ADMIN_PWD
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    networks:
      - db_link

  back-end:
    build:
      context: ./back/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - db_link

  front-end:
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80

volumes:
  mongodb_data:

networks:
  db_link: